# Auto-generated Terraform configuration
# Generated by tfstate-to-iac skill

# --- aws_autoscaling_group (1) ---

resource "aws_autoscaling_group" "eks_ai_sre_demo_nodes_56cf3349_5bb2_9022_4bef_e20e7db46f38" {
  name = "eks-ai-sre-demo-nodes-56cf3349-5bb2-9022-4bef-e20e7db46f38"
  availability_zones = [
    "us-west-2a",
    "us-west-2b"
  ]
  capacity_rebalance = true
  default_cooldown = 300
  desired_capacity = 2
  enabled_metrics = [
    "GroupAndWarmPoolDesiredCapacity",
    "GroupAndWarmPoolTotalCapacity",
    "GroupDesiredCapacity",
    "GroupInServiceCapacity",
    "GroupInServiceInstances",
    "GroupMaxSize",
    "GroupMinSize",
    "GroupPendingCapacity",
    "GroupPendingInstances",
    "GroupStandbyCapacity",
    "GroupStandbyInstances",
    "GroupTerminatingCapacity",
    "GroupTerminatingInstances",
    "GroupTerminatingRetainedCapacity",
    "GroupTerminatingRetainedInstances",
    "GroupTotalCapacity",
    "GroupTotalInstances",
    "WarmPoolDesiredCapacity",
    "WarmPoolMinSize",
    "WarmPoolPendingCapacity",
    "WarmPoolPendingRetainedCapacity",
    "WarmPoolTerminatingCapacity",
    "WarmPoolTerminatingRetainedCapacity",
    "WarmPoolTotalCapacity",
    "WarmPoolWarmedCapacity"
  ]
  health_check_grace_period = 15
  health_check_type = "EC2"
  max_size = 3
  metrics_granularity = "1Minute"
  min_size = 1
  mixed_instances_policy {
    instances_distribution = [
      {
        on_demand_allocation_strategy = "prioritized"
        on_demand_base_capacity = 0
        on_demand_percentage_above_base_capacity = 100
        spot_allocation_strategy = "lowest-price"
        spot_instance_pools = 2
        spot_max_price = ""
      }
    ]
    launch_template = [
      {
        launch_template_specification = [
          {
            launch_template_id = "lt-09941c90104dafb26"
            launch_template_name = "eks-56cf3349-5bb2-9022-4bef-e20e7db46f38"
            version = "1"
          }
        ]
        override = [
          {
            instance_requirements = []
            instance_type = "t3.medium"
            launch_template_specification = []
            weighted_capacity = ""
          }
        ]
      }
    ]
  }
  service_linked_role_arn = "arn:aws:iam::180217099948:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
  tag {
    key = "do-not-delete"
    propagate_at_launch = true
    value = "true"
  }
  tag {
    key = "donotdelete"
    propagate_at_launch = true
    value = "true"
  }
  tag {
    key = "eks:cluster-name"
    propagate_at_launch = true
    value = "ai-sre-demo"
  }
  tag {
    key = "eks:nodegroup-name"
    propagate_at_launch = true
    value = "ai-sre-demo-nodes"
  }
  tag {
    key = "k8s.io/cluster-autoscaler/ai-sre-demo"
    propagate_at_launch = true
    value = "owned"
  }
  tag {
    key = "k8s.io/cluster-autoscaler/enabled"
    propagate_at_launch = true
    value = "true"
  }
  tag {
    key = "kubernetes.io/cluster/ai-sre-demo"
    propagate_at_launch = true
    value = "owned"
  }
  tag {
    key = "project"
    propagate_at_launch = true
    value = "ai-sre-demo"
  }
  termination_policies = [
    "AllocationStrategy",
    "OldestLaunchTemplate",
    "OldestInstance"
  ]
  vpc_zone_identifier = [
    "subnet-0502e3b29ddbc5a61",
    "subnet-0bf98b66db21a26d1"
  ]
}

# --- aws_dynamodb_table (1) ---

resource "aws_dynamodb_table" "ai_sre_demo_tfstate_lock" {
  name = "ai-sre-demo-tfstate-lock"
  attribute {
    name = "LockID"
    type = "S"
  }
  billing_mode = "PAY_PER_REQUEST"
  hash_key = "LockID"
  point_in_time_recovery {
    enabled = false
  }
  table_class = "STANDARD"
  ttl {
    enabled = false
  }
  tags = {
    "DoNotDelete" = "true"
    "ManagedBy" = "terraform"
    "Project" = "ai-sre-demo"
    "do-not-delete" = "true"
  }
}

# --- aws_eks_cluster (1) ---

resource "aws_eks_cluster" "ai_sre_demo" {
  name = "ai-sre-demo"
  access_config {
    authentication_mode = "API_AND_CONFIG_MAP"
    bootstrap_cluster_creator_admin_permissions = true
  }
  role_arn = "arn:aws:iam::180217099948:role/ai-sre-demo-eks-cluster"
  upgrade_policy {
    support_type = "EXTENDED"
  }
  version = "1.31"
  vpc_config {
    cluster_security_group_id = "sg-089d2e112f21c23e9"
    endpoint_private_access = true
    endpoint_public_access = true
    public_access_cidrs = [
      "0.0.0.0/0"
    ]
    subnet_ids = [
      "subnet-0502e3b29ddbc5a61",
      "subnet-065df000346eca07d",
      "subnet-08b28a6fc070e3487",
      "subnet-0bf98b66db21a26d1"
    ]
    vpc_id = "vpc-08addde25db60cdd3"
  }
  tags = {
    "DoNotDelete" = "true"
    "Environment" = "production"
    "ManagedBy" = "terraform"
    "Project" = "ai-sre-demo"
    "do-not-delete" = "true"
    "donotdelete" = "true"
  }
}

# --- aws_iam_policy (1) ---

resource "aws_iam_policy" "arn_aws_iam__180217099948_policy_ai_sre_demo_deploy_policy" {
  name = "ai-sre-demo-deploy-policy"
  path = "/"
  policy = jsonencode({
    "Statement": [
        {
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload",
                "ecr:PutImage"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": [
                "eks:DescribeCluster",
                "eks:AccessKubernetesApi"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:eks:us-west-2:180217099948:cluster/ai-sre-demo"
        }
    ],
    "Version": "2012-10-17"
})
  tags = {
    "DoNotDelete" = "true"
    "Environment" = "production"
    "ManagedBy" = "terraform"
    "Project" = "ai-sre-demo"
    "do-not-delete" = "true"
    "donotdelete" = "true"
  }
}

# --- aws_iam_role (4) ---

resource "aws_iam_role" "ai_sre_demo_ebs_csi_driver" {
  name = "ai-sre-demo-ebs-csi-driver"
  assume_role_policy = jsonencode({
    "Statement": [
        {
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-west-2.amazonaws.com/id/1E4E0B80977A95AF0957E3806A2B8C9F:aud": "sts.amazonaws.com",
                    "oidc.eks.us-west-2.amazonaws.com/id/1E4E0B80977A95AF0957E3806A2B8C9F:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
                }
            },
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::180217099948:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/1E4E0B80977A95AF0957E3806A2B8C9F"
            }
        }
    ],
    "Version": "2012-10-17"
})
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
  ]
  max_session_duration = 3600
  path = "/"
  tags = {
    "Environment" = "production"
    "ManagedBy" = "terraform"
    "Project" = "ai-sre-demo"
    "do-not-delete" = "true"
    "donotdelete" = "true"
  }
}

resource "aws_iam_role" "ai_sre_demo_eks_cluster" {
  name = "ai-sre-demo-eks-cluster"
  assume_role_policy = jsonencode({
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
                "Service": "eks.amazonaws.com"
            }
        }
    ],
    "Version": "2012-10-17"
})
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  ]
  max_session_duration = 3600
  path = "/"
  tags = {
    "Environment" = "production"
    "ManagedBy" = "terraform"
    "Project" = "ai-sre-demo"
    "do-not-delete" = "true"
    "donotdelete" = "true"
  }
}

resource "aws_iam_role" "ai_sre_demo_eks_nodes" {
  name = "ai-sre-demo-eks-nodes"
  assume_role_policy = jsonencode({
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            }
        }
    ],
    "Version": "2012-10-17"
})
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
    "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
    "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  ]
  max_session_duration = 3600
  path = "/"
  tags = {
    "Environment" = "production"
    "ManagedBy" = "terraform"
    "Project" = "ai-sre-demo"
    "do-not-delete" = "true"
    "donotdelete" = "true"
  }
}

resource "aws_iam_role" "ai_sre_demo_github_actions_deploy" {
  name = "ai-sre-demo-github-actions-deploy"
  assume_role_policy = jsonencode({
    "Statement": [
        {
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                },
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:stackgen-demo/AI-SRE-demo-environment:*"
                }
            },
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::180217099948:oidc-provider/token.actions.githubusercontent.com"
            }
        }
    ],
    "Version": "2012-10-17"
})
  managed_policy_arns = [
    "arn:aws:iam::180217099948:policy/ai-sre-demo-deploy-policy"
  ]
  max_session_duration = 3600
  path = "/"
  tags = {
    "Environment" = "production"
    "ManagedBy" = "terraform"
    "Project" = "ai-sre-demo"
    "do-not-delete" = "true"
    "donotdelete" = "true"
  }
}

# --- aws_iam_role_policy_attachment (6) ---

resource "aws_iam_role_policy_attachment" "ai_sre_demo_ebs_csi_driver_arn_aws_iam__aws_policy_service_role_amazonebscsidriverpolicy" {
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
  role = "ai-sre-demo-ebs-csi-driver"
}

resource "aws_iam_role_policy_attachment" "ai_sre_demo_eks_cluster_arn_aws_iam__aws_policy_amazoneksclusterpolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  role = "ai-sre-demo-eks-cluster"
}

resource "aws_iam_role_policy_attachment" "ai_sre_demo_eks_nodes_arn_aws_iam__aws_policy_amazonec2containerregistryreadonly" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
  role = "ai-sre-demo-eks-nodes"
}

resource "aws_iam_role_policy_attachment" "ai_sre_demo_eks_nodes_arn_aws_iam__aws_policy_amazoneks_cni_policy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role = "ai-sre-demo-eks-nodes"
}

resource "aws_iam_role_policy_attachment" "ai_sre_demo_eks_nodes_arn_aws_iam__aws_policy_amazoneksworkernodepolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
  role = "ai-sre-demo-eks-nodes"
}

resource "aws_iam_role_policy_attachment" "ai_sre_demo_github_actions_deploy_arn_aws_iam__180217099948_policy_ai_sre_demo_deploy_policy" {
  policy_arn = "arn:aws:iam::180217099948:policy/ai-sre-demo-deploy-policy"
  role = "ai-sre-demo-github-actions-deploy"
}

# --- aws_s3_bucket (1) ---

resource "aws_s3_bucket" "ai_sre_demo_tfstate" {
  bucket = "ai-sre-demo-tfstate"
  tags = {
    "DoNotDelete" = "true"
    "ManagedBy" = "terraform"
    "Project" = "ai-sre-demo"
    "do-not-delete" = "true"
  }
}
