# Auto-generated Terraform configuration
# Generated by tfstate-to-iac skill

# --- aws_cloudwatch_log_group (1) ---

resource "aws_cloudwatch_log_group" "_aws_lambda_hello_kitty_serve" {
  name = "/aws/lambda/hello-kitty-serve"
  retention_in_days = 7
  tags = {
    "Application" = "hello-kitty"
    "Environment" = "demo"
    "Repository" = "sample-apps-infra"
    "Terraform" = "true"
  }
}

# --- aws_iam_policy (2) ---

resource "aws_iam_policy" "arn_aws_iam__180217099948_policy_hello_kitty_serve_inline" {
  name = "hello-kitty-serve-inline"
  path = "/"
  policy = jsonencode({
    "Statement": [
        {
            "Action": "s3:GetObject",
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::hello-kitty-images-renewing-alpaca/*",
            "Sid": "s3"
        }
    ],
    "Version": "2012-10-17"
})
  tags = {
    "Application" = "hello-kitty"
    "Environment" = "demo"
    "Repository" = "sample-apps-infra"
    "Terraform" = "true"
  }
}

resource "aws_iam_policy" "arn_aws_iam__180217099948_policy_hello_kitty_serve_logs" {
  name = "hello-kitty-serve-logs"
  path = "/"
  policy = jsonencode({
    "Statement": [
        {
            "Action": [
                "logs:PutLogEvents",
                "logs:CreateLogStream",
                "logs:CreateLogGroup"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:logs:us-west-2:180217099948:log-group:/aws/lambda/hello-kitty-serve:*:*",
                "arn:aws:logs:us-west-2:180217099948:log-group:/aws/lambda/hello-kitty-serve:*"
            ]
        }
    ],
    "Version": "2012-10-17"
})
  tags = {
    "Application" = "hello-kitty"
    "Environment" = "demo"
    "Repository" = "sample-apps-infra"
    "Terraform" = "true"
  }
}

# --- aws_iam_role (1) ---

resource "aws_iam_role" "hello_kitty_serve" {
  name = "hello-kitty-serve"
  assume_role_policy = jsonencode({
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
                "Service": "lambda.amazonaws.com"
            }
        }
    ],
    "Version": "2012-10-17"
})
  max_session_duration = 3600
  path = "/"
  tags = {
    "Application" = "hello-kitty"
    "Environment" = "demo"
    "Repository" = "sample-apps-infra"
    "Terraform" = "true"
  }
}

# --- aws_lambda_function (1) ---

resource "aws_lambda_function" "hello_kitty_serve" {
  description = "Hello Kitty image server"
  architectures = [
    "x86_64"
  ]
  environment {
    variables = {
      IMAGES_BUCKET = "hello-kitty-images-renewing-alpaca"
    }
  }
  ephemeral_storage {
    size = 512
  }
  function_name = "hello-kitty-serve"
  handler = "main.lambda_handler"
  logging_config {
    log_format = "Text"
    log_group = "/aws/lambda/hello-kitty-serve"
  }
  memory_size = 128
  package_type = "Zip"
  reserved_concurrent_executions = -1
  role = "arn:aws:iam::180217099948:role/hello-kitty-serve"
  runtime = "python3.8"
  timeout = 3
  tracing_config {
    mode = "PassThrough"
  }
  tags = {
    "Application" = "hello-kitty"
    "Environment" = "demo"
    "Repository" = "sample-apps-infra"
    "Terraform" = "true"
  }
  filename = "/dev/null"  # placeholder — deployed via CI/CD

  lifecycle {
    ignore_changes = [source_code_hash, filename]
  }
}

# --- aws_s3_bucket (1) ---

resource "aws_s3_bucket" "hello_kitty_images_renewing_alpaca" {
  bucket = "hello-kitty-images-renewing-alpaca"
  tags = {
    "Application" = "hello-kitty"
    "Environment" = "demo"
    "Repository" = "sample-apps-infra"
    "Terraform" = "true"
  }
}
