# Auto-generated Terraform configuration
# Generated by tfstate-to-iac skill

# --- aws_cloudwatch_log_group (3) ---

resource "aws_cloudwatch_log_group" "_aws_lambda_retroboard_api" {
  name = "/aws/lambda/retroboard-api"
  retention_in_days = 7
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

resource "aws_cloudwatch_log_group" "_aws_lambda_retroboard_send_email" {
  name = "/aws/lambda/retroboard-send-email"
  retention_in_days = 7
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

resource "aws_cloudwatch_log_group" "_aws_lambda_retroboard_slack_alerts" {
  name = "/aws/lambda/retroboard-slack-alerts"
  retention_in_days = 7
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

# --- aws_dynamodb_table (1) ---

resource "aws_dynamodb_table" "boards" {
  name = "boards"
  attribute {
    name = "board_id"
    type = "S"
  }
  attribute {
    name = "sk"
    type = "S"
  }
  billing_mode = "PAY_PER_REQUEST"
  hash_key = "board_id"
  point_in_time_recovery {
    enabled = false
  }
  range_key = "sk"
  table_class = "STANDARD"
  ttl {
    enabled = false
  }
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Name" = "boards"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

# --- aws_iam_policy (5) ---

resource "aws_iam_policy" "arn_aws_iam__180217099948_policy_retroboard_api_inline" {
  name = "retroboard-api-inline"
  path = "/"
  policy = jsonencode({
    "Statement": [
        {
            "Action": [
                "dynamodb:UpdateItem",
                "dynamodb:Scan",
                "dynamodb:Query",
                "dynamodb:PutItem",
                "dynamodb:GetItem",
                "dynamodb:DeleteItem"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:dynamodb:us-west-2:180217099948:table/boards",
            "Sid": "dynamodb"
        },
        {
            "Action": "sns:Publish",
            "Effect": "Allow",
            "Resource": "arn:aws:sns:us-west-2:180217099948:retroboard-alerts",
            "Sid": "sns"
        },
        {
            "Action": "sqs:SendMessage",
            "Effect": "Allow",
            "Resource": "arn:aws:sqs:us-west-2:180217099948:retroboard-emails",
            "Sid": "sqssendmessage"
        }
    ],
    "Version": "2012-10-17"
})
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

resource "aws_iam_policy" "arn_aws_iam__180217099948_policy_retroboard_api_logs" {
  name = "retroboard-api-logs"
  path = "/"
  policy = jsonencode({
    "Statement": [
        {
            "Action": [
                "logs:PutLogEvents",
                "logs:CreateLogStream",
                "logs:CreateLogGroup"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:logs:us-west-2:180217099948:log-group:/aws/lambda/retroboard-api:*:*",
                "arn:aws:logs:us-west-2:180217099948:log-group:/aws/lambda/retroboard-api:*"
            ]
        }
    ],
    "Version": "2012-10-17"
})
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

resource "aws_iam_policy" "arn_aws_iam__180217099948_policy_retroboard_send_email_inline" {
  name = "retroboard-send-email-inline"
  path = "/"
  policy = jsonencode({
    "Statement": [
        {
            "Action": "ses:SendTemplatedEmail",
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "sessendemail"
        }
    ],
    "Version": "2012-10-17"
})
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

resource "aws_iam_policy" "arn_aws_iam__180217099948_policy_retroboard_send_email_logs" {
  name = "retroboard-send-email-logs"
  path = "/"
  policy = jsonencode({
    "Statement": [
        {
            "Action": [
                "logs:PutLogEvents",
                "logs:CreateLogStream",
                "logs:CreateLogGroup"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:logs:us-west-2:180217099948:log-group:/aws/lambda/retroboard-send-email:*:*",
                "arn:aws:logs:us-west-2:180217099948:log-group:/aws/lambda/retroboard-send-email:*"
            ]
        }
    ],
    "Version": "2012-10-17"
})
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

resource "aws_iam_policy" "arn_aws_iam__180217099948_policy_retroboard_slack_alerts_logs" {
  name = "retroboard-slack-alerts-logs"
  path = "/"
  policy = jsonencode({
    "Statement": [
        {
            "Action": [
                "logs:PutLogEvents",
                "logs:CreateLogStream",
                "logs:CreateLogGroup"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:logs:us-west-2:180217099948:log-group:/aws/lambda/retroboard-slack-alerts:*:*",
                "arn:aws:logs:us-west-2:180217099948:log-group:/aws/lambda/retroboard-slack-alerts:*"
            ]
        }
    ],
    "Version": "2012-10-17"
})
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

# --- aws_iam_role (3) ---

resource "aws_iam_role" "retroboard_api" {
  name = "retroboard-api"
  assume_role_policy = jsonencode({
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
                "Service": "lambda.amazonaws.com"
            }
        }
    ],
    "Version": "2012-10-17"
})
  max_session_duration = 3600
  path = "/"
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

resource "aws_iam_role" "retroboard_send_email" {
  name = "retroboard-send-email"
  assume_role_policy = jsonencode({
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
                "Service": "lambda.amazonaws.com"
            }
        }
    ],
    "Version": "2012-10-17"
})
  max_session_duration = 3600
  path = "/"
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

resource "aws_iam_role" "retroboard_slack_alerts" {
  name = "retroboard-slack-alerts"
  assume_role_policy = jsonencode({
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
                "Service": "lambda.amazonaws.com"
            }
        }
    ],
    "Version": "2012-10-17"
})
  max_session_duration = 3600
  path = "/"
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

# --- aws_lambda_function (2) ---

resource "aws_lambda_function" "retroboard_send_email" {
  description = "send email with ses, read email content from sqs messages"
  architectures = [
    "x86_64"
  ]
  environment {
    variables = {
      SES_SENDER_EMAIL_ADDRESS = "notifications+demo@stackgen.com"
    }
  }
  ephemeral_storage {
    size = 512
  }
  function_name = "retroboard-send-email"
  handler = "main.lambda_handler"
  logging_config {
    log_format = "Text"
    log_group = "/aws/lambda/retroboard-send-email"
  }
  memory_size = 128
  package_type = "Zip"
  reserved_concurrent_executions = -1
  role = "arn:aws:iam::180217099948:role/retroboard-send-email"
  runtime = "python3.8"
  timeout = 3
  tracing_config {
    mode = "PassThrough"
  }
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
    "terraform-aws-modules" = "lambda"
  }
  filename = "/dev/null"  # placeholder — deployed via CI/CD

  lifecycle {
    ignore_changes = [source_code_hash, filename]
  }
}

resource "aws_lambda_function" "retroboard_slack_alerts" {
  description = "send slack alerts for retroboard"
  architectures = [
    "arm64"
  ]
  environment {
    variables = {
      SLACK_WEBHOOK_URL = "REDACTED_SLACK_WEBHOOK_URL"
    }
  }
  ephemeral_storage {
    size = 512
  }
  function_name = "retroboard-slack-alerts"
  handler = "main.lambda_handler"
  logging_config {
    log_format = "Text"
    log_group = "/aws/lambda/retroboard-slack-alerts"
  }
  memory_size = 128
  package_type = "Zip"
  reserved_concurrent_executions = -1
  role = "arn:aws:iam::180217099948:role/retroboard-slack-alerts"
  runtime = "python3.8"
  timeout = 3
  tracing_config {
    mode = "PassThrough"
  }
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
    "terraform-aws-modules" = "lambda"
  }
  filename = "/dev/null"  # placeholder — deployed via CI/CD

  lifecycle {
    ignore_changes = [source_code_hash, filename]
  }
}

# --- aws_s3_bucket (1) ---

resource "aws_s3_bucket" "retroboard_demo_appcd_io" {
  bucket = "retroboard.demo.appcd.io"
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

# --- aws_sns_topic (1) ---

resource "aws_sns_topic" "arn_aws_sns_us_west_2_180217099948_retroboard_alerts" {
  name = "retroboard-alerts"
  policy = "{\"Statement\":[{\"Action\":[\"sns:Subscribe\",\"sns:SetTopicAttributes\",\"sns:RemovePermission\",\"sns:Publish\",\"sns:ListSubscriptionsByTopic\",\"sns:GetTopicAttributes\",\"sns:DeleteTopic\",\"sns:AddPermission\"],\"Condition\":{\"StringEquals\":{\"AWS:SourceOwner\":\"180217099948\"}},\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"},\"Resource\":\"arn:aws:sns:us-west-2:180217099948:retroboard-alerts\",\"Sid\":\"__default_statement_ID\"}],\"Version\":\"2012-10-17\"}"
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}

# --- aws_sqs_queue (1) ---

resource "aws_sqs_queue" "https___sqs_us_west_2_amazonaws_com_180217099948_retroboard_emails" {
  name = "retroboard-emails"
  kms_data_key_reuse_period_seconds = 300
  max_message_size = 262144
  message_retention_seconds = 345600
  policy = "{\"Id\":\"arn:aws:sqs:ap-south-1:[object Promise]:undefined/SQSDefaultPolicy\",\"Statement\":[{\"Action\":\"SQS:SendMessage\",\"Condition\":{\"ArnLike\":{\"aws:SourceArn\":\"arn:aws:sns:ap-south-1:180217099948:c2c-test.fifo\"}},\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"sns.amazonaws.com\"},\"Resource\":\"arn:aws:sqs:us-west-2:180217099948:retroboard-emails\",\"Sid\":\"topic-subscription-arn:aws:sns:ap-south-1:180217099948:c2c-test.fifo\"}],\"Version\":\"2012-10-17\"}"
  sqs_managed_sse_enabled = true
  visibility_timeout_seconds = 30
  tags = {
    "Application" = "retroboard"
    "Environment" = "sandbox"
    "Repository" = "infra"
    "Terraform" = "true"
  }
}
