# Auto-generated Terraform configuration
# Generated by tfstate-to-iac skill

# --- aws_route53_record (23) ---

resource "aws_route53_record" "_hostedzone_z0666492yr9b6f8pg8u4__56fb46583cf7cdf49425da762ad7c90d_terminal_demo_stackgen_com__cname" {
  name = "_56fb46583cf7cdf49425da762ad7c90d.terminal.demo.stackgen.com"
  records = [
    "_deacdf8a066376154cc1f9df44a97c24.xlfgrmvvlj.acm-validations.aws."
  ]
  ttl = 60
  type = "CNAME"
  zone_id = "/hostedzone/Z0666492YR9B6F8PG8U4"
}

resource "aws_route53_record" "_hostedzone_z0666492yr9b6f8pg8u4__9e222e2e253629332c2c4e27bfa85b75_demo_stackgen_com__cname" {
  name = "_9e222e2e253629332c2c4e27bfa85b75.demo.stackgen.com"
  records = [
    "_433eca41424c3a1f6dbfb93f86bb8379.djqtsrsxkq.acm-validations.aws."
  ]
  ttl = 300
  type = "CNAME"
  zone_id = "/hostedzone/Z0666492YR9B6F8PG8U4"
}

resource "aws_route53_record" "_hostedzone_z0666492yr9b6f8pg8u4__ae7e9d578d847894ace948d5ff8180bd_status_kuma_demo_stackgen_com__cname" {
  name = "_ae7e9d578d847894ace948d5ff8180bd.status.kuma.demo.stackgen.com"
  records = [
    "_9ec786ad1e9872f7cc09334d82156d1e.jkddzztszm.acm-validations.aws."
  ]
  ttl = 300
  type = "CNAME"
  zone_id = "/hostedzone/Z0666492YR9B6F8PG8U4"
}

resource "aws_route53_record" "_hostedzone_z0666492yr9b6f8pg8u4__f8882513d4ab42bdf2410718e0f870e7_logs_demo_stackgen_com__cname" {
  name = "_f8882513d4ab42bdf2410718e0f870e7.logs.demo.stackgen.com"
  records = [
    "_d608e93a988a408562ebdf7f671a05e9.jkddzztszm.acm-validations.aws."
  ]
  ttl = 300
  type = "CNAME"
  zone_id = "/hostedzone/Z0666492YR9B6F8PG8U4"
}

resource "aws_route53_record" "_hostedzone_z0666492yr9b6f8pg8u4__fc5dcc8d143c22978a959acfd5231db3_kuma_demo_stackgen_com__cname" {
  name = "_fc5dcc8d143c22978a959acfd5231db3.kuma.demo.stackgen.com"
  records = [
    "_a71de5d5ca35af317caa5a9b8e6f1cb3.jkddzztszm.acm-validations.aws."
  ]
  ttl = 300
  type = "CNAME"
  zone_id = "/hostedzone/Z0666492YR9B6F8PG8U4"
}

resource "aws_route53_record" "_hostedzone_z0666492yr9b6f8pg8u4_demo_stackgen_com__ns" {
  name = "demo.stackgen.com"
  records = [
    "ns-1040.awsdns-02.org.",
    "ns-1775.awsdns-29.co.uk.",
    "ns-343.awsdns-42.com.",
    "ns-947.awsdns-54.net."
  ]
  ttl = 172800
  type = "NS"
  zone_id = "/hostedzone/Z0666492YR9B6F8PG8U4"
}

resource "aws_route53_record" "_hostedzone_z0666492yr9b6f8pg8u4_demo_stackgen_com__soa" {
  name = "demo.stackgen.com"
  records = [
    "ns-1775.awsdns-29.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"
  ]
  ttl = 900
  type = "SOA"
  zone_id = "/hostedzone/Z0666492YR9B6F8PG8U4"
}

resource "aws_route53_record" "_hostedzone_z0666492yr9b6f8pg8u4_logs_demo_stackgen_com__a" {
  name = "logs.demo.stackgen.com"
  alias {
    evaluate_target_health = true
    name = "dualstack.k8s-signoz-signozin-f013c5093a-1737068213.us-west-2.elb.amazonaws.com"
    zone_id = "Z1H1FL5HABSF5"
  }
  type = "A"
  zone_id = "/hostedzone/Z0666492YR9B6F8PG8U4"
}

resource "aws_route53_record" "_hostedzone_z0666492yr9b6f8pg8u4_retroboard_demo_stackgen_com__a" {
  name = "retroboard.demo.stackgen.com"
  alias {
    evaluate_target_health = true
    name = "d3bwjxax1pld8s.cloudfront.net"
    zone_id = "Z2FDTNDATAQYW2"
  }
  type = "A"
  zone_id = "/hostedzone/Z0666492YR9B6F8PG8U4"
}

resource "aws_route53_record" "_hostedzone_z0666492yr9b6f8pg8u4_status_kuma_demo_stackgen_com__a" {
  name = "status.kuma.demo.stackgen.com"
  alias {
    evaluate_target_health = true
    name = "k8s-uptimekumaauthent-21952d60ef-694073190.us-west-2.elb.amazonaws.com"
    zone_id = "Z1H1FL5HABSF5"
  }
  type = "A"
  zone_id = "/hostedzone/Z0666492YR9B6F8PG8U4"
}

resource "aws_route53_record" "_hostedzone_z0666492yr9b6f8pg8u4_terminal_demo_stackgen_com__a" {
  name = "terminal.demo.stackgen.com"
  alias {
    evaluate_target_health = true
    name = "k8s-terminal-terminal-a3c27c6fe0-1093999360.us-west-1.elb.amazonaws.com"
    zone_id = "Z368ELLRRE2KJ0"
  }
  type = "A"
  zone_id = "/hostedzone/Z0666492YR9B6F8PG8U4"
}

resource "aws_route53_record" "_hostedzone_z0919566osvcsp5866s7__110a10fcd5ccb2e979d9f35e5381c906_enterprisetest_appcd_io__cname" {
  name = "_110a10fcd5ccb2e979d9f35e5381c906.enterprisetest.appcd.io"
  records = [
    "_b69d58da766241b9b9ec41f92c65da0c.mhbtsbpdnt.acm-validations.aws."
  ]
  ttl = 300
  type = "CNAME"
  zone_id = "/hostedzone/Z0919566OSVCSP5866S7"
}

resource "aws_route53_record" "_hostedzone_z0919566osvcsp5866s7_enterprisetest_appcd_io__a" {
  name = "enterprisetest.appcd.io"
  alias {
    evaluate_target_health = true
    name = "a51d68257f3cd4779b7b9dc2242608d5-da37d6252f102a99.elb.us-east-1.amazonaws.com"
    zone_id = "Z26RNL4JYFTOTI"
  }
  type = "A"
  zone_id = "/hostedzone/Z0919566OSVCSP5866S7"
}

resource "aws_route53_record" "_hostedzone_z0919566osvcsp5866s7_enterprisetest_appcd_io__ns" {
  name = "enterprisetest.appcd.io"
  records = [
    "ns-1521.awsdns-62.org.",
    "ns-1598.awsdns-07.co.uk.",
    "ns-417.awsdns-52.com.",
    "ns-723.awsdns-26.net."
  ]
  ttl = 172800
  type = "NS"
  zone_id = "/hostedzone/Z0919566OSVCSP5866S7"
}

resource "aws_route53_record" "_hostedzone_z0919566osvcsp5866s7_enterprisetest_appcd_io__soa" {
  name = "enterprisetest.appcd.io"
  records = [
    "ns-1598.awsdns-07.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"
  ]
  ttl = 900
  type = "SOA"
  zone_id = "/hostedzone/Z0919566OSVCSP5866S7"
}

resource "aws_route53_record" "_hostedzone_z0965387ihyqb8ukj8x6__5dbb555f027f7846404c3ece8560cf32_retroboard_demo_appcd_io__cname" {
  name = "_5dbb555f027f7846404c3ece8560cf32.retroboard.demo.appcd.io"
  records = [
    "_65f4b93eac61c1af17ba18473fd195fc.djqtsrsxkq.acm-validations.aws."
  ]
  ttl = 300
  type = "CNAME"
  zone_id = "/hostedzone/Z0965387IHYQB8UKJ8X6"
}

resource "aws_route53_record" "_hostedzone_z0965387ihyqb8ukj8x6__78eca873951c614f9d4eb3e10007a88c_demo_appcd_io__cname" {
  name = "_78eca873951c614f9d4eb3e10007a88c.demo.appcd.io"
  records = [
    "_1eaaaa774758f08215838e1422b67a36.djqtsrsxkq.acm-validations.aws."
  ]
  ttl = 300
  type = "CNAME"
  zone_id = "/hostedzone/Z0965387IHYQB8UKJ8X6"
}

resource "aws_route53_record" "_hostedzone_z0965387ihyqb8ukj8x6__dbe77ae8af09053ba6f2debfcbc33906_on_prem_demo_appcd_io__cname" {
  name = "_dbe77ae8af09053ba6f2debfcbc33906.on-prem.demo.appcd.io"
  records = [
    "_8928128713b8e41cdb67b9d72f30c889.sdgjtdhdhz.acm-validations.aws."
  ]
  ttl = 300
  type = "CNAME"
  zone_id = "/hostedzone/Z0965387IHYQB8UKJ8X6"
}

resource "aws_route53_record" "_hostedzone_z0965387ihyqb8ukj8x6__fad5b995e99cb46cd2a22b7260b09541_test_demo_appcd_io__cname" {
  name = "_fad5b995e99cb46cd2a22b7260b09541.test.demo.appcd.io"
  records = [
    "_35d01ca18f98183805c9c21b967f39d3.sdgjtdhdhz.acm-validations.aws."
  ]
  ttl = 300
  type = "CNAME"
  zone_id = "/hostedzone/Z0965387IHYQB8UKJ8X6"
}

resource "aws_route53_record" "_hostedzone_z0965387ihyqb8ukj8x6_demo_appcd_io__ns" {
  name = "demo.appcd.io"
  records = [
    "ns-1293.awsdns-33.org.",
    "ns-1937.awsdns-50.co.uk.",
    "ns-362.awsdns-45.com.",
    "ns-835.awsdns-40.net."
  ]
  ttl = 172800
  type = "NS"
  zone_id = "/hostedzone/Z0965387IHYQB8UKJ8X6"
}

resource "aws_route53_record" "_hostedzone_z0965387ihyqb8ukj8x6_demo_appcd_io__soa" {
  name = "demo.appcd.io"
  records = [
    "ns-1937.awsdns-50.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"
  ]
  ttl = 900
  type = "SOA"
  zone_id = "/hostedzone/Z0965387IHYQB8UKJ8X6"
}

resource "aws_route53_record" "_hostedzone_z0965387ihyqb8ukj8x6_retroboard_demo_appcd_io__a" {
  name = "retroboard.demo.appcd.io"
  alias {
    evaluate_target_health = true
    name = "d3bwjxax1pld8s.cloudfront.net"
    zone_id = "Z2FDTNDATAQYW2"
  }
  type = "A"
  zone_id = "/hostedzone/Z0965387IHYQB8UKJ8X6"
}

resource "aws_route53_record" "_hostedzone_z0965387ihyqb8ukj8x6_test_demo_appcd_io__a" {
  name = "test.demo.appcd.io"
  alias {
    evaluate_target_health = true
    name = "a62acfbfe7bdc4ec4986eeb602e567de-cf40d5b51213011f.elb.us-west-2.amazonaws.com"
    zone_id = "Z18D5FSROUN65G"
  }
  type = "A"
  zone_id = "/hostedzone/Z0965387IHYQB8UKJ8X6"
}

# --- aws_ses_active_receipt_rule_set (1) ---

resource "aws_ses_active_receipt_rule_set" "testaccessdenied" {
  rule_set_name = "testaccessdenied"
}

# --- aws_ses_domain_dkim (9) ---

resource "aws_ses_domain_dkim" "asif_appcd_com" {
  domain = "asif@appcd.com"
}

resource "aws_ses_domain_dkim" "demo_mailer_stackgen_com" {
  domain = "demo.mailer.stackgen.com"
}

resource "aws_ses_domain_dkim" "gaurav_appcd_com" {
  domain = "gaurav@appcd.com"
}

resource "aws_ses_domain_dkim" "jigar_appcd_com" {
  domain = "jigar@appcd.com"
}

resource "aws_ses_domain_dkim" "kunal_appcd_com" {
  domain = "kunal@appcd.com"
}

resource "aws_ses_domain_dkim" "niraj_appcd_com" {
  domain = "niraj@appcd.com"
}

resource "aws_ses_domain_dkim" "nirajftw_gmail_com" {
  domain = "nirajftw@gmail.com"
}

resource "aws_ses_domain_dkim" "notifications_stackgen_com" {
  domain = "notifications@stackgen.com"
}

resource "aws_ses_domain_dkim" "vishwajeet_stackgen_com" {
  domain = "vishwajeet@stackgen.com"
}

# --- aws_ses_domain_identity (9) ---

resource "aws_ses_domain_identity" "asif_appcd_com" {
  domain = "asif@appcd.com"
}

resource "aws_ses_domain_identity" "demo_mailer_stackgen_com" {
  domain = "demo.mailer.stackgen.com"
}

resource "aws_ses_domain_identity" "gaurav_appcd_com" {
  domain = "gaurav@appcd.com"
}

resource "aws_ses_domain_identity" "jigar_appcd_com" {
  domain = "jigar@appcd.com"
}

resource "aws_ses_domain_identity" "kunal_appcd_com" {
  domain = "kunal@appcd.com"
}

resource "aws_ses_domain_identity" "niraj_appcd_com" {
  domain = "niraj@appcd.com"
}

resource "aws_ses_domain_identity" "nirajftw_gmail_com" {
  domain = "nirajftw@gmail.com"
}

resource "aws_ses_domain_identity" "notifications_stackgen_com" {
  domain = "notifications@stackgen.com"
}

resource "aws_ses_domain_identity" "vishwajeet_stackgen_com" {
  domain = "vishwajeet@stackgen.com"
}

# --- aws_ses_domain_mail_from (18) ---

resource "aws_ses_domain_mail_from" "BEUtG" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "vishwajeet@stackgen.com"
}

resource "aws_ses_domain_mail_from" "HcueC" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "jigar@appcd.com"
}

resource "aws_ses_domain_mail_from" "IiODz" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "asif@appcd.com"
}

resource "aws_ses_domain_mail_from" "Peqlt" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "gaurav@appcd.com"
}

resource "aws_ses_domain_mail_from" "TrrzY" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "niraj@appcd.com"
}

resource "aws_ses_domain_mail_from" "asif_appcd_com" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "asif@appcd.com"
}

resource "aws_ses_domain_mail_from" "dULmM" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "notifications@stackgen.com"
}

resource "aws_ses_domain_mail_from" "demo_mailer_stackgen_com" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "demo.mailer.stackgen.com"
}

resource "aws_ses_domain_mail_from" "gaurav_appcd_com" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "gaurav@appcd.com"
}

resource "aws_ses_domain_mail_from" "jigar_appcd_com" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "jigar@appcd.com"
}

resource "aws_ses_domain_mail_from" "kunal_appcd_com" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "kunal@appcd.com"
}

resource "aws_ses_domain_mail_from" "lQsCh" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "kunal@appcd.com"
}

resource "aws_ses_domain_mail_from" "niraj_appcd_com" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "niraj@appcd.com"
}

resource "aws_ses_domain_mail_from" "nirajftw_gmail_com" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "nirajftw@gmail.com"
}

resource "aws_ses_domain_mail_from" "notifications_stackgen_com" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "notifications@stackgen.com"
}

resource "aws_ses_domain_mail_from" "pcjLp" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "nirajftw@gmail.com"
}

resource "aws_ses_domain_mail_from" "rVLms" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "demo.mailer.stackgen.com"
}

resource "aws_ses_domain_mail_from" "vishwajeet_stackgen_com" {
  behavior_on_mx_failure = "UseDefaultValue"
  domain = "vishwajeet@stackgen.com"
}

# --- aws_ses_receipt_rule (1) ---

resource "aws_ses_receipt_rule" "testaccessdenied_accessdenied" {
  name = "accessdenied"
  enabled = true
  rule_set_name = "testaccessdenied"
  scan_enabled = true
  tls_policy = "Optional"
}

# --- aws_ses_receipt_rule_set (1) ---

resource "aws_ses_receipt_rule_set" "testaccessdenied" {
  rule_set_name = "testaccessdenied"
}

# --- aws_ses_template (1) ---

resource "aws_ses_template" "retroboard_summary" {
  name = "retroboard-summary"
  html = "<h3>{{board_slug}} - Summary of your board</h3>\n<p>Total Notes: {{total_notes}}</p>\n<p>Total Votes: {{total_votes}}</p>\n\n<p>Notes:</p>\n<pre>{{notes_text}}</pre>"
  subject = "{{board_slug}} - Summary of your board"
  text = "{{board_slug}} - Summary of your board\n\nTotal Notes: {{total_notes}}\nTotal Votes: {{total_votes}}\n\nNotes:\n{{notes_text}}"
}
