# Auto-generated Terraform configuration
# Generated by tfstate-to-iac skill

# --- aws_route53_delegation_set (1) ---

resource "aws_route53_delegation_set" "_delegationset_n063972335eghkjkdp6mr" {
}

# --- aws_route53_resolver_rule_association (4) ---

resource "aws_route53_resolver_rule_association" "rslvr_autodefined_assoc_vpc_02814c9f8a44aee3d_internet_resolver" {
  resolver_rule_id = "rslvr-autodefined-rr-internet-resolver"
  vpc_id = "vpc-02814c9f8a44aee3d"
}

resource "aws_route53_resolver_rule_association" "rslvr_autodefined_assoc_vpc_03aecb1e85e749ec9_internet_resolver" {
  resolver_rule_id = "rslvr-autodefined-rr-internet-resolver"
  vpc_id = "vpc-03aecb1e85e749ec9"
}

resource "aws_route53_resolver_rule_association" "rslvr_autodefined_assoc_vpc_06cab6363775ce4b0_internet_resolver" {
  resolver_rule_id = "rslvr-autodefined-rr-internet-resolver"
  vpc_id = "vpc-06cab6363775ce4b0"
}

resource "aws_route53_resolver_rule_association" "rslvr_autodefined_assoc_vpc_08addde25db60cdd3_internet_resolver" {
  resolver_rule_id = "rslvr-autodefined-rr-internet-resolver"
  vpc_id = "vpc-08addde25db60cdd3"
}

# --- aws_route53_zone (3) ---

resource "aws_route53_zone" "_hostedzone_z0666492yr9b6f8pg8u4" {
  name = "demo.stackgen.com"
  tags = {
    "team" = "platform"
  }
}

resource "aws_route53_zone" "_hostedzone_z0919566osvcsp5866s7" {
  name = "enterprisetest.appcd.io"
}

resource "aws_route53_zone" "_hostedzone_z0965387ihyqb8ukj8x6" {
  name = "demo.appcd.io"
  tags = {
    "team" = "platform"
  }
}
