# Auto-generated Terraform configuration
# Generated by tfstate-to-iac skill

# --- aws_cloudfront_distribution (1) ---

resource "aws_cloudfront_distribution" "e1v0q90q7e9yjo" {
  aliases = [
    "retroboard.demo.appcd.io",
    "retroboard.demo.stackgen.com"
  ]
  default_cache_behavior {
    allowed_methods = [
      "GET",
      "HEAD"
    ]
    cache_policy_id = "658327ea-f89d-4fab-a63d-7e88639e58f6"
    cached_methods = [
      "GET",
      "HEAD"
    ]
    compress = true
    grpc_config = [
      {
        enabled = false
      }
    ]
    target_origin_id = "retroboard.demo.appcd.io.s3-website-us-west-2.amazonaws.com"
    viewer_protocol_policy = "redirect-to-https"
  }
  enabled = false
  http_version = "http2"
  is_ipv6_enabled = true
  origin {
    connection_attempts = 3
    connection_timeout = 10
    custom_origin_config = [
      {
        http_port = 80
        https_port = 443
        origin_keepalive_timeout = 5
        origin_protocol_policy = "http-only"
        origin_read_timeout = 30
        origin_ssl_protocols = [
          "SSLv3",
          "TLSv1",
          "TLSv1.1",
          "TLSv1.2"
        ]
      }
    ]
    domain_name = "retroboard.demo.appcd.io.s3-website-us-west-2.amazonaws.com"
    origin_id = "retroboard.demo.appcd.io.s3-website-us-west-2.amazonaws.com"
  }
  price_class = "PriceClass_All"
  restrictions {
    geo_restriction = [
      {
        locations = []
        restriction_type = "none"
      }
    ]
  }
  retain_on_delete = false
  viewer_certificate {
    acm_certificate_arn = "arn:aws:acm:us-east-1:180217099948:certificate/f2c38549-5b88-4385-9d10-7b6c2d4e1109"
    minimum_protocol_version = "TLSv1.2_2021"
    ssl_support_method = "sni-only"
  }
  wait_for_deployment = true
  tags = {
    "team" = "platform"
  }
}

# --- aws_cloudwatch_metric_alarm (1) ---

resource "aws_cloudwatch_metric_alarm" "aws_aidevops_ec2_cpu_test" {
  actions_enabled = true
  alarm_name = "AWS-AIDevOps-EC2-CPU-Test"
  comparison_operator = "GreaterThanThreshold"
  dimensions = {
    InstanceId = "i-07306f78f234c47e2"
  }
  evaluation_periods = 1
  metric_name = "CPUUtilization"
  namespace = "AWS/EC2"
  period = 60
  statistic = "Average"
  threshold = 70
  treat_missing_data = "notBreaching"
}

# --- aws_sns_topic_policy (1) ---

resource "aws_sns_topic_policy" "arn_aws_sns_us_west_2_180217099948_retroboard_alerts" {
  policy = jsonencode({
    "Statement": [
        {
            "Action": [
                "sns:Subscribe",
                "sns:SetTopicAttributes",
                "sns:RemovePermission",
                "sns:Publish",
                "sns:ListSubscriptionsByTopic",
                "sns:GetTopicAttributes",
                "sns:DeleteTopic",
                "sns:AddPermission"
            ],
            "Condition": {
                "StringEquals": {
                    "AWS:SourceOwner": "180217099948"
                }
            },
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Resource": "arn:aws:sns:us-west-2:180217099948:retroboard-alerts",
            "Sid": "__default_statement_ID"
        }
    ],
    "Version": "2012-10-17"
})
}
