# Auto-generated Terraform configuration
# Generated by tfstate-to-iac skill

# --- aws_internet_gateway (1) ---

resource "aws_internet_gateway" "workshop_igw" {
  tags = {
    "Component" = "network"
    "ManagedBy" = "Terraform"
    "Name" = "workshop-igw"
    "Project" = "workshop"
    "do-not-delete" = "true"
  }
}

# --- aws_rds_global_cluster (1) ---

resource "aws_rds_global_cluster" "my_global_cluster" {
  engine = "aurora-mysql"
  engine_lifecycle_support = "open-source-rds-extended-support"
  engine_version = "8.0.mysql_aurora.3.04.0"
  global_cluster_identifier = "my-global-cluster"
  storage_encrypted = true
}
