# Auto-generated Terraform configuration
# Generated by tfstate-to-iac skill

# --- aws_iam_instance_profile (1) ---

resource "aws_iam_instance_profile" "guild_mcp_server" {
  name = "guild-mcp-server"
  path = "/"
  role = "guild-mcp-server"
  tags = {
    "do-not-delete" = "true"
    "ttl" = "-1"
  }
}

# --- aws_iam_openid_connect_provider (1) ---

resource "aws_iam_openid_connect_provider" "guild_mcp_eks_irsa" {
  client_id_list = [
    "sts.amazonaws.com"
  ]
  thumbprint_list = [
    "06b25927c42a721631c1efd9431e648fa62e1e39"
  ]
  url = "https://oidc.eks.us-west-1.amazonaws.com/id/1FB640E861E71BD2B54CB44BC5FB7C80"
  tags = {
    "Name" = "guild-mcp-eks-irsa"
    "do-not-delete" = "true"
    "ttl" = "-1"
  }
}

# --- aws_iam_policy (2) ---

resource "aws_iam_policy" "arn_aws_iam__180217099948_policy_guild_mcp_cluster_20260430163129684700000003" {
  name = "guild-mcp-cluster-20260430163129684700000003"
  name_prefix = "guild-mcp-cluster-"
  path = "/"
  policy = jsonencode({
    "Statement": [
        {
            "Action": [
                "ec2:RunInstances",
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "$${aws:PrincipalTag/eks:eks-cluster-name}"
                },
                "StringLike": {
                    "aws:RequestTag/eks:kubernetes-node-class-name": "*",
                    "aws:RequestTag/eks:kubernetes-node-pool-name": "*"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "Compute"
        },
        {
            "Action": [
                "ec2:CreateVolume",
                "ec2:CreateSnapshot"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "$${aws:PrincipalTag/eks:eks-cluster-name}"
                }
            },
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*:*:volume/*",
                "arn:aws:ec2:*:*:snapshot/*"
            ],
            "Sid": "Storage"
        },
        {
            "Action": "ec2:CreateNetworkInterface",
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "$${aws:PrincipalTag/eks:eks-cluster-name}",
                    "aws:RequestTag/eks:kubernetes-cni-node-name": "*"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "Networking"
        },
        {
            "Action": [
                "elasticloadbalancing:CreateTargetGroup",
                "elasticloadbalancing:CreateRule",
                "elasticloadbalancing:CreateLoadBalancer",
                "elasticloadbalancing:CreateListener",
                "ec2:CreateSecurityGroup"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "$${aws:PrincipalTag/eks:eks-cluster-name}"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "LoadBalancer"
        },
        {
            "Action": "shield:CreateProtection",
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "$${aws:PrincipalTag/eks:eks-cluster-name}"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "ShieldProtection"
        },
        {
            "Action": "shield:TagResource",
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "$${aws:PrincipalTag/eks:eks-cluster-name}"
                }
            },
            "Effect": "Allow",
            "Resource": "arn:aws:shield::*:protection/*",
            "Sid": "ShieldTagResource"
        }
    ],
    "Version": "2012-10-17"
})
  tags = {
    "do-not-delete" = "true"
    "ttl" = "-1"
  }
}

resource "aws_iam_policy" "arn_aws_iam__180217099948_policy_guild_mcp_cluster_clusterencryption20260430163150721900000010" {
  description = "Cluster encryption policy to allow cluster role to utilize CMK provided"
  name = "guild-mcp-cluster-ClusterEncryption20260430163150721900000010"
  name_prefix = "guild-mcp-cluster-ClusterEncryption"
  path = "/"
  policy = jsonencode({
    "Statement": [
        {
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ListGrants",
                "kms:DescribeKey"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:kms:us-west-1:180217099948:key/b58254c2-f6ed-4a04-b80d-e2e062cb2b18"
        }
    ],
    "Version": "2012-10-17"
})
  tags = {
    "do-not-delete" = "true"
    "ttl" = "-1"
  }
}

# --- aws_iam_role (3) ---

resource "aws_iam_role" "guild_mcp_cluster_20260430163129678700000002" {
  name = "guild-mcp-cluster-20260430163129678700000002"
  assume_role_policy = jsonencode({
    "Statement": [
        {
            "Action": [
                "sts:TagSession",
                "sts:AssumeRole"
            ],
            "Effect": "Allow",
            "Principal": {
                "Service": "eks.amazonaws.com"
            },
            "Sid": "EKSClusterAssumeRole"
        }
    ],
    "Version": "2012-10-17"
})
  max_session_duration = 3600
  path = "/"
  tags = {
    "do-not-delete" = "true"
    "ttl" = "-1"
  }
}

resource "aws_iam_role" "guild_mcp_server" {
  name = "guild-mcp-server"
  assume_role_policy = jsonencode({
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            }
        }
    ],
    "Version": "2012-10-17"
})
  max_session_duration = 3600
  path = "/"
  tags = {
    "do-not-delete" = "true"
    "ttl" = "-1"
  }
}

resource "aws_iam_role" "guild_mcp_server_irsa" {
  name = "guild-mcp-server-irsa"
  assume_role_policy = jsonencode({
    "Statement": [
        {
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-west-1.amazonaws.com/id/1FB640E861E71BD2B54CB44BC5FB7C80:aud": "sts.amazonaws.com",
                    "oidc.eks.us-west-1.amazonaws.com/id/1FB640E861E71BD2B54CB44BC5FB7C80:sub": "system:serviceaccount:default:guild-mcp-server"
                }
            },
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::180217099948:oidc-provider/oidc.eks.us-west-1.amazonaws.com/id/1FB640E861E71BD2B54CB44BC5FB7C80"
            }
        }
    ],
    "Version": "2012-10-17"
})
  max_session_duration = 3600
  path = "/"
  tags = {
    "do-not-delete" = "true"
    "ttl" = "-1"
  }
}
