# Auto-generated Terraform configuration
# Generated by tfstate-to-iac skill

# --- aws_dynamodb_table (2) ---

resource "aws_dynamodb_table" "KrrLB" {
  name = "180217099948-states-lock"
  attribute {
    name = "LockID"
    type = "S"
  }
  billing_mode = "PAY_PER_REQUEST"
  hash_key = "LockID"
  point_in_time_recovery {
    enabled = true
  }
  server_side_encryption {
    enabled = true
  }
  table_class = "STANDARD"
  ttl {
    enabled = false
  }
  tags = {
    "Attributes" = "states-lock"
    "Name" = "180217099948-states-lock"
    "Namespace" = "180217099948"
    "Repository" = "infra"
  }
}

resource "aws_dynamodb_table" "sg_deployment_test_statefiles_lock" {
  name = "sg-deployment-test-statefiles-lock"
  attribute {
    name = "LockID"
    type = "S"
  }
  billing_mode = "PAY_PER_REQUEST"
  hash_key = "LockID"
  point_in_time_recovery {
    enabled = true
  }
  server_side_encryption {
    enabled = true
  }
  table_class = "STANDARD"
  ttl {
    enabled = false
  }
  tags = {
    "Attributes" = "lock"
    "Name" = "sg-deployment-test-statefiles-lock"
    "Namespace" = "sg-deployment-test-statefiles"
    "created-by" = "nasir"
    "do-not-delete" = "true"
    "purpose" = "store statefile for stackgen apply"
    "statefile-storage-location" = "provision_test"
    "who-has-the-statefile" = "nasir-mac"
  }
}

# --- aws_s3_bucket (8) ---

resource "aws_s3_bucket" "aiden_eval_reports" {
  bucket = "aiden-eval-reports"
  tags = {
    "owner" = "Gaurav Chavan"
    "purpose" = "aiden evaluation report"
    "team" = "qa"
  }
}

resource "aws_s3_bucket" "aiden_reports" {
  bucket = "aiden-reports"
  tags = {
    "do-not-delete" = "true"
    "owner" = "Gaurav Chavan"
    "purpose" = "aiden-reports"
  }
}

resource "aws_s3_bucket" "digant_test_state" {
  bucket = "digant-test-state"
  tags = {
    "do-not-delete" = "true"
  }
}

resource "aws_s3_bucket" "jaingounchained_mcp_deploy_backends" {
  bucket = "jaingounchained-mcp-deploy-backends"
  tags = {
    "created-by" = "jaingounchained"
    "do-not-delete" = "true"
  }
}

resource "aws_s3_bucket" "nsrk_test_delete_me" {
  bucket = "nsrk-test-delete-me"
  tags = {
    "owner" = "nsrk"
  }
}

resource "aws_s3_bucket" "pxgDx" {
  bucket = "180217099948-states"
  tags = {
    "Attributes" = "state"
    "Name" = "180217099948-states"
    "Namespace" = "180217099948"
    "Repository" = "infra"
  }
}

resource "aws_s3_bucket" "sg_deployment_test_statefiles" {
  bucket = "sg-deployment-test-statefiles"
  tags = {
    "Name" = "sg-deployment-test-statefiles"
    "Namespace" = "sg-deployment-test-statefiles"
    "created-by" = "nasir"
    "do-not-delete" = "true"
    "purpose" = "store statefile for stackgen apply"
    "statefile-storage-location" = "provision_test"
    "who-has-the-statefile" = "nasir-mac"
  }
}

resource "aws_s3_bucket" "workshop_lambda_code_bucket_180217099948" {
  bucket = "workshop-lambda-code-bucket-180217099948"
  tags = {
    "Component" = "app-source"
    "ManagedBy" = "Terraform"
    "Project" = "workshop"
    "do-not-delete" = "true"
  }
}
